use std::error::Error;

use image::{DynamicImage, GenericImageView, Rgba, RgbaImage};
use oc_root::geo::WorldVec2;

// WARNING: module generated by AI then hand modified

/// Even-odd ray casting point-in-polygon test.
fn inside(poly: &[WorldVec2], x: f32, y: f32) -> bool {
    let mut result = false;
    let mut j = poly.len() - 1;

    for i in 0..poly.len() {
        let (xi, yi) = (poly[i].x, poly[i].y);
        let (xj, yj) = (poly[j].x, poly[j].y);
        if (yi > y) != (yj > y) && x < (xj - xi) * (y - yi) / (yj - yi) + xi {
            result = !result;
        }
        j = i;
    }

    result
}

pub fn crop_polygon(
    image: &DynamicImage,
    points: &[WorldVec2],
) -> Result<RgbaImage, Box<dyn Error>> {
    let (w, h) = image.dimensions();

    // Bounding box of the polygon, clamped to the image.
    let min_x = points.iter().map(|p| p.x).fold(f32::INFINITY, f32::min);
    let max_x = points.iter().map(|p| p.x).fold(f32::NEG_INFINITY, f32::max);
    let min_y = points.iter().map(|p| p.y).fold(f32::INFINITY, f32::min);
    let max_y = points.iter().map(|p| p.y).fold(f32::NEG_INFINITY, f32::max);

    let x0 = min_x.floor().max(0.0) as u32;
    let y0 = min_y.floor().max(0.0) as u32;
    let x1 = (max_x.ceil().max(0.0) as u32).min(w);
    let y1 = (max_y.ceil().max(0.0) as u32).min(h);

    if x0 >= x1 || y0 >= y1 {
        return Err("polygon lies outside the image".into());
    }

    // Transparent canvas the size of the bounding box.
    let mut out = RgbaImage::from_pixel(x1 - x0, y1 - y0, Rgba([0, 0, 0, 0]));

    for y in y0..y1 {
        for x in x0..x1 {
            if inside(points, x as f32 + 0.5, y as f32 + 0.5) {
                out.put_pixel(x - x0, y - y0, image.get_pixel(x, y));
            }
        }
    }

    Ok(out)
}
